### PR TITLE
Very small function to basescraper to pull image_blob from passed url instead of just selectormap

### PR DESCRIPTION
**Pull request by Darklyter**

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
Why not change then `get_image_blob` method to something like that?
```python
 def get_image_blob(self, response):
    if 'image_blob' not in self.get_selector_map():
        return None

    if self.get_selector_map('image_blob'):
        image = self.get_image(response)
        return self.get_image_blob_from_link(image)

    return None
```

**Comment by Darklyter** [comment]
Could, but would have to add a second parameter to use the passed url instead of the selector map.  Seemed easier to just add the function

**Comment by DirtyRacer1337** [comment]
I mean where is refactoring, you have duplicates
```python
    def get_image_blob(self, response):
        if 'image_blob' not in self.get_selector_map():
            return None

        if self.get_selector_map('image_blob'):
            image = self.get_image(response)
            if image:
                image = self.format_link(response, image)
                req = Http.get(image, headers=self.headers, cookies=self.cookies)
                if req and req.ok:
                    return base64.b64encode(req.content).decode('utf-8')

        return None

    def get_image_blob_from_link(self, image):
        if image:
            req = Http.get(image, headers=self.headers, cookies=self.cookies)
            if req and req.ok:
                return base64.b64encode(req.content).decode('utf-8')
        return None
```

instead
```python
 def get_image_blob(self, response):
    if 'image_blob' not in self.get_selector_map():
        return None

    if self.get_selector_map('image_blob'):
        image = self.get_image(response)
        return self.get_image_blob_from_link(image)

    return None

def get_image_blob_from_link(self, image):
    if image:
        req = Http.get(image, headers=self.headers, cookies=self.cookies)
        if req and req.ok:
            return base64.b64encode(req.content).decode('utf-8')

    return None
```

**Comment by Darklyter** [comment]
Ohhh...  I get it now.  Looks good to me.  Let me snag that real quick...

Ok, tweaked.  I really need to try to think more Pythony.

**Pull request merged**
